# Generated by Django 5.2.3 on 2025-07-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Ruta Segura desde la PUCE al CCI en Trole', max_length=200)),
                ('descripcion', models.TextField(help_text='Describe los pasos, paradas, y cualquier consejo útil.')),
                ('punto_inicio', models.CharField(help_text="Ej: 'Universidad PUCE (Av. 12 de Octubre)'", max_length=255)),
                ('punto_destino', models.CharField(help_text="Ej: 'Centro Comercial Iñaquito (CCI)'", max_length=255)),
                ('tipo_transporte', models.CharField(choices=[('BUS', 'Bus'), ('TROLE', 'Trolebús / Ecovía'), ('BICI', 'Bicicleta'), ('PIE', 'A pie'), ('AUTO', 'Auto'), ('OTRO', 'Otro')], default='BUS', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
